### PR TITLE
Clean up meson.build (Fixed PR against main branch)

### PR DESCRIPTION
**Pull request by godalming123**
This makes a few changes to the `meson.build` file that fix one warning, and make it slightly more readable.

### CODE REVIEW

**Comment by godalming123** [comment]
(I can make this into one commit if you want)

**Comment by ehopperdietzel** [comment]
Hey, thanks for your feedback. I've tested it on Debian, and it compiles smoothly without any issues. However, I did run into problems with library dependencies on Red Hat distros in the past, which is why I included the library paths array. I plan to retest it on Red Hat distros, and if everything checks out, I'll proceed with the merge.

Which distro are you using btw?

**Comment by ehopperdietzel** [comment]
Tested it and everything is working ;)

**Comment by godalming123** [comment]
I am using fedora, and am finding that in order to run the example (found at this projects readme), I have to set the `LD_LIBRARY_PATH` enviroment variable first.

**Comment by ehopperdietzel** [comment]
Yes, I had previously hardcoded the `/usr/lib` path for library installation, but I've now removed it. Meson should now install the library in the default distribution library directory. On Fedora, running `sudo ldconfig` after installing the library is necessary to update the shared library cache.

**Pull request merged**
