### PR TITLE
build: heed results from pkg-config

### PR DESCRIPTION
**Pull request by jengelh**
The .pc files can have extra required flags or locations (e.g. if libraries are installed outside the standard search paths).

### CODE REVIEW

**Comment by ehopperdietzel** [comment]
Thank you very much! I'll run some tests before merging your changes. Based on past experiences, it seems that other users haven't encountered issues with building and installing it. Are you currently attempting to build RPM packages? Additionally, I'm not particularly well-versed in pkg-config, so are you suggesting that I need to create a .pc file containing include paths and other configurations? While exploring the [Wayland meson.build](https://gitlab.freedesktop.org/wayland/wayland/-/blob/main/src/meson.build?ref_type=heads) file for guidance, I noticed they use the following approach:

```
pkgconfig.generate(
		wayland_client,
		name: 'Wayland Client',
		description: 'Wayland client side library',
		version: meson.project_version(),
		filebase: 'wayland-client',
		variables: [
			'datarootdir=' + join_paths('${prefix}', get_option('datadir')),
			'pkgdatadir=' + join_paths('${datarootdir}', meson.project_name())
		]
	)
```

Does this generate the .pc file, which is then installed?

**Comment by ehopperdietzel** [comment]
Thanks, I merged the changes, removed the ld.sh script and also added pkg.generate() in meson.build, so now pkg-config can find it.

**Comment by jengelh** [comment]
>other users haven't encountered issues with building and installing it

low usercount.

>are you suggesting that I need to create a .pc file

could be useful for louvre, but not a requirement.

**Comment by ehopperdietzel** [comment]
Thanks again, I have one more question, do you think it is a good idea to install headers in `/usr/include/SRM` now that I am using pkgconfig, should I let meson choose the path?

**Comment by ehopperdietzel** [comment]
I think `default_headers_install_path = join_paths(get_option('prefix'), get_option('includedir'))` does the job.

**Pull request merged**
